---
version: 1

kind: experiment

tags: [ Longitudinal_Covid ] # change this to some other name e.g. MONAI_2D_Pathologies

description: "Longitudinal Covid Example" # add some beautiful description

build:
  image: pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime
  build_steps:
    - apt update
    - pip3 freeze
    - pip install -r requirements.txt
    - wandb login d15aaa61714a0a8f19f06381750cb1072708297b


environment:
  #affinity:
  #  nodeAffinity:
  #    requiredDuringSchedulingIgnoredDuringExecution:
  #      nodeSelectorTerms:
  #        - matchExpressions:
  #            - key: kubernetes.io/hostname
  #             operator: In
  #              values:
  #                - rishi
  resources:
    cpu:
      requests: 1
      limits: 1
    memory:
      requests: 16000
    gpu:
      requests: 1
      limits: 1

params:
  config_file: modules/segmentation_longitudinal/config/config_segmentation_longitudinal.yml
  data_root: /data/jorge_perez/dyndata
  output_path: /outputs/jorge_padilla/covidseg/experiments/
  gpus : 1
  device: cuda


run:
    cmd:
      #- pip install dynamic-dataset-0.0.1.tar.gz --force
      - python -u train.py -c {{config_file}}
          --data_root={{data_root}} \
          --gpus={{ gpus }} \
      #    --on_polyaxon
      # to list all files that were pushed to polyaxon - ls -al
      # to get the working directory on polyaxon - pwd